apiVersion: v1
kind: Service
metadata:
  name: mediapipe-fastapi
  labels:
    app: mediapipe-fastapi
spec:
  selector:
    app: mediapipe-fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP