apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/websocket-services: "api-gateway-service"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - cuecode.kr
    - www.cuecode.kr
    secretName: cuecode-tls-secret
  rules:
  - host: www.cuecode.kr
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway-service
            port:
              number: 13000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-ui-service
            port:
              number: 14000
  - host: cuecode.kr
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway-service
            port:
              number: 13000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-ui-service
            port:
              number: 14000