apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - cuecode.kr
    - www.cuecode.kr
    secretName: cuecode-tls-secret
  rules:
  - host: www.cuecode.kr
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway-service
            port:
              number: 13000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-ui-service
            port:
              number: 14000
  - host: cuecode.kr
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway-service
            port:
              number: 13000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-ui-service
            port:
              number: 14000