spring:
  application:
    name: motion

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_DB}

server:
  port: 15000
#  address: 0.0.0.0


#server:
#  port: 15000

#spring:
#  application:
#    name: motion
#  data:
#    mongodb:
#      uri: mongodb://poly:poly1234@localhost:27017/motionDB

