name: CueCode CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  ACR_RESOURCE_GROUP: cuecode-rg
  AZURE_CONTAINER_REGISTRY: cuecoderegistry
  CLUSTER_NAME: cuecode-k8s
  CLUSTER_RESOURCE_GROUP: cuecode-rg
  CLUSTER_RESOURCE_TYPE: Microsoft.ContainerService/managedClusters
  NAMESPACE: default
  AUTH_TYPE: SERVICE_PRINCIPAL

jobs:
  build_and_deploy_config_server:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: ${{ env.AUTH_TYPE }}

      - name: Log into ACR
        run: az acr login -n ${{ env.AZURE_CONTAINER_REGISTRY }}

      - name: Set up Gradle and Cache
        uses: gradle/actions/setup-gradle@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build Spring Boot app with Gradle (Skip Tests)
        working-directory: ./SpringConfigServer
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Build and push image to ACR
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/spring-config-server:${{ github.sha }} -f ./SpringConfigServer/Dockerfile ./SpringConfigServer
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/spring-config-server:${{ github.sha }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Get K8s context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'
          resource-type: ${{ env.CLUSTER_RESOURCE_TYPE }}

      - name: Deploys application
        uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: |
            ./SpringConfigServer/k8s/deployment.yaml
            ./SpringConfigServer/k8s/service.yaml
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/spring-config-server:${{ github.sha }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          name: ${{ env.CLUSTER_NAME }}
          namespace: ${{ env.NAMESPACE }}
          resource-type: ${{ env.CLUSTER_RESOURCE_TYPE }}

  build_and_deploy_services:
    needs: build_and_deploy_config_server
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - { name: 'ApiGateway', container_name: 'api-gateway' }
          - { name: 'FrontUI', container_name: 'front-ui' }
          - { name: 'MotionService', container_name: 'motion-service' }
          - { name: 'UserService', container_name: 'user-service' }
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: ${{ env.AUTH_TYPE }}

      - name: Log into ACR
        run: az acr login -n ${{ env.AZURE_CONTAINER_REGISTRY }}

      - name: Set up Gradle and Cache
        uses: gradle/actions/setup-gradle@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build Spring Boot app with Gradle (Skip Tests)
        working-directory: ./${{ matrix.service.name }}
        run: |
          chmod +x ./gradlew
          ./gradlew build -x test

      - name: Build and push image to ACR
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ matrix.service.container_name }}:${{ github.sha }} -f ./${{ matrix.service.name }}/Dockerfile ./${{ matrix.service.name }}
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ matrix.service.container_name }}:${{ github.sha }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Get K8s context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'
          resource-type: ${{ env.CLUSTER_RESOURCE_TYPE }}

      - name: Deploys application
        uses: Azure/k8s-deploy@v5
        with:
          action: deploy
          manifests: |
            ./${{ matrix.service.name }}/k8s/deployment.yaml
            ./${{ matrix.service.name }}/k8s/service.yaml
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ matrix.service.container_name }}:${{ github.sha }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
          name: ${{ env.CLUSTER_NAME }}
          namespace: ${{ env.NAMESPACE }}
          resource-type: ${{ env.CLUSTER_RESOURCE_TYPE }}
